# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CINQTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CINQTest
	pod 'Alamofire'
	pod 'Kingfisher'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Realm'
	pod 'RxRealm'
	pod 'RxRealmDataSources'
	pod 'RxAlamofire'
	pod 'RxAlamofire+ObjectMapper'
end
